#!/usr/bin/env mksh
# -*- mode: sh -*-

# needs root on remote system
# updates all config files that already exist locally

LC_ALL=C; export LC_ALL
unset LANGUAGE

set -e
set -o pipefail
cd "$(dirname "$0")"

for x in *.xml; do
	print -nr -- "I: Processing $x…"
	x=${x%.xml}

	ssh -n -l root ci-busyapps.lan.tarent.de "
		cat /var/lib/jenkins/jobs/${x@Q}/config.xml
		echo
	    " | sed --posix \
	    -e 's!\([&]\)apos[;]!\1#39;!g' \
	    -e 's!\([&]\)quot[;]!\1#34;!g' \
	    >"$x.xml~"

	while IFS= read -r line; do
		print -r -- "$line"
		[[ $line = '    <hudson.security.AuthorizationMatrixProperty>' ]] || \
		    continue
		while IFS= read -r line; do
			[[ $line = '    </hudson.security.AuthorizationMatrixProperty>' ]] && \
			    break
			print -r -- "$line"
		done | sort -u
		print -r -- '    </hudson.security.AuthorizationMatrixProperty>'
	done <"$x.xml~" >"$x.xml"
	print " done."
done
rm -f *~
print "I: All done, success."
